name: Automatic Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Generate Semantic Version
      id: semver
      run: |
        version=$(git log -1 --pretty=%B | grep -oP 'v[0-9]+\.[0-9]+\.[0-9]+' || git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
        while git rev-parse "$version" >/dev/null 2>&1; do
          version=$(echo $version | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
        done
        echo "version=$version" >> $GITHUB_OUTPUT
    
    - name: Create Git Tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag "${{ steps.semver.outputs.version }}"
        git push origin "${{ steps.semver.outputs.version }}"
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.semver.outputs.version }}
        generate_release_notes: true
        files: |
          SpotUp.bat
